import sec1Book from '../../assets/courseProgram/fa_book.svg';
export const item = [
    {
        img: sec1Book,
        module: '1 модуль',
        nameModule: 'Організаційний',
        lesson1: 'Урок 1: Як буде проходити навчання',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Мотивація та постановка цілей',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Загальні правила та спілкування',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Звідки в Телеграмі гроші? ТГ VS Інші соцмедіа',
        lesson4HighLight: 'Урок 4:',
    },
    {
        img: sec1Book,
        module: '2 модуль',
        nameModule: 'Фундамент',
        lesson1: 'Урок 1: Термінологія, функціонал та можливості',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Тематика каналів. Прибуткові ТГ ніши',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Види заробітку на ТГ',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Безпека в ТГ',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: ФОП та сплата податків',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Прийом оплат на ФОП, картку та на крипто-гаманець',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Формати присутності: канали, чати і групи',
        lesson7HighLight: 'Урок 7:',
        lesson8: 'Урок 8: Взаємодія та відносини з іншими учасниками ринку',
        lesson8HighLight: 'Урок 8:',
    },
    {
        img: sec1Book,
        module: '3 модуль',
        nameModule: 'Початок роботи з ТГ каналами',
        lesson1: 'Урок 1: Створення та використання чат-ботів',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Базова упаковка каналу',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Базовий постинг та оформлення',
        lesson3HighLight: 'Урок 3:',
    },
    {
        img: sec1Book,
        module: '4 модуль',
        nameModule: 'Інструментарій',
        lesson1: 'Урок 1: Статистика ТГ каналів',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Повний огляд TGStat. Частина перша',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Повний огляд TGStat. Частина друга',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Повний огляд TGStat. Частина третя',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Повний огляд TGStat. Частина четверта',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Повний огляд Telemetr',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Повний огляд Telemetrio',
        lesson7HighLight: 'Урок 7:',
        lesson8: 'Урок 8: ТГ боти',
        lesson8HighLight: 'Урок 8:',
        lesson9: 'Урок 9: ТГ боти для постингу',
        lesson9HighLight: 'Урок 9:',
        lesson10: 'Урок 10: ТГ боти для привітань',
        lesson10HighLight: 'Урок 10:',
        lesson11: 'Урок 11: ТГ  Додаткові сервіси та боти для роботи з ТГ',
        lesson11HighLight: 'Урок 11:',
    }
]

export const item2 = [
    {
        img: sec1Book,
        module: '5 модуль',
        nameModule: 'Телеграм-професії',
        lesson1: 'Урок 1: Філософія фрілансера',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Розбір ТГ послуг і заробітку',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Пошук роботи та клієнтів',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Спілкування з клієнтами та обробка заперечень',
        lesson4HighLight: 'Урок 4:',
    },
    {
        img: sec1Book,
        module: '6 модуль',
        nameModule: 'Контент-менеджер',
        lesson1: 'Урок 1: Види контенту',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Де шукати контент?',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Формати публікацій в різних тематиках',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: СММ стратегія та контент-план в залежності від тематики каналу',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Відкладений постінг',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Робота з візуалом',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Використання ШІ та нейромереж',
        lesson7HighLight: 'Урок 7:',
    },
    {
        img: sec1Book,
        module: '7 модуль',
        nameModule: 'Менеджер з продажу реклами',
        lesson1: 'Урок 1: Пошук роботи менеджером з продажу реклами',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Пошук рекламодавців',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Співпраця з зовнішніми рекламодавцями',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Формати і види реклами',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Ціноутрверення і СРМ',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Спам',
        lesson6HighLight: 'Урок 6:',
    },
    {
        img: sec1Book,
        module: '8 модуль',
        nameModule: 'Медіа-баєр',
        lesson1: 'Урок 1: Де шукати роботу медіа-баєром',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Створення робочих креативів',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Тести рекламних креативів',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Де шукати канали на закуп реклами?',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Використання сервісів аналітики у роботі медіа баєра',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Закуп реклами та масштабування',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Оцінка ефективності закупу',
        lesson7HighLight: 'Урок 7:',
    },
    {
        img: sec1Book,
        module: '9 модуль',
        nameModule: 'Адміністратор ТГ каналів',
        lesson1: 'Урок 1: Адміністрування ТГ каналів',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Прийом заявок',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Звітність',
        lesson3HighLight: 'Урок 3:',  
    },
]

export const item3 = [
    {
        img: sec1Book,
        module: '10 модуль',
        nameModule: 'Перелив трафіку (УБТ)',
        lesson1: 'Урок 1: Перелив аудиторії з зовнішніх ресурсів',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Вибір тематики та особливості ціноутворення',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Перелив аудиторії з ТікТок',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Тікток акаунти',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Монтаж і уніфікація відео',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Перелив аудиторії з Інстаграм та ФБ ТІКТОК',
        lesson6HighLight: 'Урок 6:',
    },
    {
        img: sec1Book,
        module: '11 модуль',
        nameModule: 'Заробіток на ТГ каналах',
        lesson1: 'Урок 1: Мій досвід в побудові ТГ імперії',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Найперспективніші тематики в ТГ',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Монетизація ТГ каналу',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Партнерські програми та арбітраж трафіку',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Набір аудиторії. Платні методи просування',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: TG Ads',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Окупність тг каналів',
        lesson7HighLight: 'Урок 7:',
        lesson8: 'Урок 8: Перепродаж ТГ каналів',
        lesson8HighLight: 'Урок 8:',
    },
    {
        img: sec1Book,
        module: '12 модуль',
        nameModule: 'Покупка ТГ каналів',
        lesson1: 'Урок 1: Перепродаж ТГ каналів',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Аналіз тг каналу перед купівлею',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Процес купівлі каналу та гарантії безпеки',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Зміна тематики каналу після придбання',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Нюанси та аспекти по продажу ТГ каналу',
        lesson5HighLight: 'Урок 5:',
    },
    {
        img: sec1Book,
        module: '13 модуль',
        nameModule: 'Масштабування',
        lesson1: 'Урок 1: Побудова команди',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Створення та масштабування команди з УБТ трафіку',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Створення мережі тг каналів',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Пошук та залучення інвестора',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Створення агенції для надання послуг в ТГ',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Бухгалтерський облік та юридичні аспекти',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Політична реклама в Телеграм',
        lesson7HighLight: 'Урок 7:',
    },
    {
        img: sec1Book,
        module: '14 модуль',
        nameModule: 'Запуски в Телеграм та продаж інфопродуктів',
        lesson1: 'Урок 1: Персональний бренд',
        lesson1HighLight: 'Урок 1:',
        lesson2: 'Урок 2: Створення біржі купівлі-продажу ТГ каналів',
        lesson2HighLight: 'Урок 2:',
        lesson3: 'Урок 3: Визначення напрямку експертності та підбір інфопродукту',
        lesson3HighLight: 'Урок 3:',
        lesson4: 'Урок 4: Розпакування особистості',
        lesson4HighLight: 'Урок 4:',
        lesson5: 'Урок 5: Стратегія запуска та створення контент-плану',
        lesson5HighLight: 'Урок 5:',
        lesson6: 'Урок 6: Воронка запуску',
        lesson6HighLight: 'Урок 6:',
        lesson7: 'Урок 7: Контент під час запусків в ТГ',
        lesson7HighLight: 'Урок 7:',
    },
]